title: PARS Improvement Proposals (PIPs)
description: Governance proposals for the Cyrus Protocol ecosystem
url: "https://pips.cyrus.vote"
baseurl: ""

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Include markdown files
include:
  - PIPs
  - README.md
  - CNAME

# Exclude unnecessary files
exclude:
  - .github/
  - LICENSE
  - "*.log"
